/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rotary_phone.glb 
Author: jacques_3D (https://sketchfab.com/jacques_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rotary-phone-dd6cd63f0bec4c41b5cba2855d22b29b
Title: Rotary Phone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Phone3d(props) {
  const { nodes, materials } = useGLTF('/models/rotary_phone.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -59.849, 0]}>
          <group position={[0, 66.378, 0]}>
            <mesh geometry={nodes.box_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
            <mesh geometry={nodes.hand_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
            <mesh geometry={nodes.body_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
            <mesh geometry={nodes.cycale_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
            <mesh geometry={nodes.metal_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
            <mesh geometry={nodes.cycale_numbers_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
          </group>
          <mesh geometry={nodes.table_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
          <mesh geometry={nodes.cable_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
          <mesh geometry={nodes.cable_2_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/rotary_phone.glb')
